// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import MainNavigation from "@/components/MainNavigation";
import { AuthProvider } from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IsaLabs - Guia de Desenvolvimento Infantil",
  description: "Aplicativo para pais e cuidadores com atividades de desenvolvimento para crianças de 1-5 anos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <MainNavigation />
          {children}
          
          {/* Rodapé Global */}
          <footer className="bg-gray-900 text-white">
            <div className="container mx-auto px-4 py-8">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                {/* Logo e Descrição */}
                <div className="md:col-span-2">
                  <div className="flex items-center gap-3 mb-4">
                    <img 
                      src="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/9de3e442-281e-4f62-8b95-cd94a151e2b6.png" 
                      alt="IsaLabs Logo" 
                      className="h-8 w-auto"
                    />
                    <h3 className="text-xl font-bold">IsaLabs</h3>
                  </div>
                  <p className="text-gray-300 text-sm mb-4">
                    Plataforma completa de desenvolvimento infantil com atividades educativas 
                    para crianças de 1 a 5 anos. Desenvolvido com amor para pais e cuidadores.
                  </p>
                  <div className="flex items-center gap-4 text-sm text-gray-400">
                    <span>© 2024 IsaLabs</span>
                    <span>•</span>
                    <span>Todos os direitos reservados</span>
                  </div>
                </div>

                {/* Links Legais */}
                <div>
                  <h4 className="font-semibold mb-3">Legal</h4>
                  <ul className="space-y-2 text-sm text-gray-300">
                    <li>
                      <a href="/terms" className="hover:text-white transition-colors">
                        Termos de Uso
                      </a>
                    </li>
                    <li>
                      <a href="/privacy" className="hover:text-white transition-colors">
                        Política de Privacidade
                      </a>
                    </li>
                    <li>
                      <a href="/cookies" className="hover:text-white transition-colors">
                        Política de Cookies
                      </a>
                    </li>
                  </ul>
                </div>

                {/* Suporte */}
                <div>
                  <h4 className="font-semibold mb-3">Suporte</h4>
                  <ul className="space-y-2 text-sm text-gray-300">
                    <li>
                      <a href="/help" className="hover:text-white transition-colors">
                        Central de Ajuda
                      </a>
                    </li>
                    <li>
                      <a href="/contact" className="hover:text-white transition-colors">
                        Contato
                      </a>
                    </li>
                    <li>
                      <a href="/faq" className="hover:text-white transition-colors">
                        FAQ
                      </a>
                    </li>
                  </ul>
                </div>
              </div>

              {/* Linha divisória */}
              <div className="border-t border-gray-700 mt-8 pt-6">
                <div className="flex flex-col md:flex-row justify-between items-center text-sm text-gray-400">
                  <p>
                    Desenvolvido com ❤️ para o desenvolvimento infantil
                  </p>
                  <div className="flex items-center gap-4 mt-4 md:mt-0">
                    <span>Versão 1.0.0</span>
                    <span>•</span>
                    <span>Brasil</span>
                  </div>
                </div>
              </div>
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}